services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend:
    build: ./backend
    container_name: spring-backend
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/ai_resume_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    volumes:
      - h2_data:/data
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: react-frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  h2_data: