services:

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: ai_resume_screening
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    ports:
      - "5672:5672"  
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest


  backend:
    build: ./backend
    container_name: spring-backend
    depends_on:
      - db
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ai_resume_screening?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8080:8080"


  frontend:
    build: ./frontend 
    container_name: react-frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data: