server.port=8080

spring.application.name=ai-resume-screening

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thutrinh2442@gmail.com
spring.mail.password=gtjmgvanxmjsrxdb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.profiles.active=dev
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true



cloudinary.cloud-name=dt3btnnxy
cloudinary.api-key=463966291979622
cloudinary.api-secret=qh9cOXw9UUo-BKRyFl6OTY-FYis

openai.model=gpt-4o-mini
openai.api.key =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



