server.port=8080

spring.application.name=ai-resume-screening

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thutrinh2442@gmail.com
spring.mail.password=gtjmgvanxmjsrxdb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.profiles.active=dev

cloudinary.cloud-name=dt3btnnxy
cloudinary.api-key=463966291979622
cloudinary.api-secret=qh9cOXw9UUo-BKRyFl6OTY-FYis




