server.port=8080

spring.application.name=ai-resume-screening

spring.profiles.active=dev

cloudinary.cloud-name=dt3btnnxy
cloudinary.api-key=463966291979622
cloudinary.api-secret=qh9cOXw9UUo-BKRyFl6OTY-FYis